name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Installing Lua 5.1 interpreter
        run: sudo apt-get install lua5.1

      - name: Running all tests on Lua 5.1
        run: "sh -c 'lua test.lua tests/*'"

      - name: Replacing Lua 5.1 interpreter with LuaJIT
        run: |
          sudo apt-get remove lua5.1
          sudo apt-get install luajit

      - name: Running all tests on LuaJIT
        run: "sh -c 'LUA_PATH=\"./?.lua\" luajit test.lua tests/*'"
